import numpy as np
from generator import make_classification

class LinearSVC:
    """Linear SVC classifier.
    
    Parameters
    ------------
    eta : float
      Learning rate (between 0.0 and 1.0)
    n_iter : int
      Passes over the training dataset.
    random_state : int
      Random number generator seed for random weight 
      initialization.
    
    Attributes
    -----------
    w_ : 1d-array
      Weights after fitting.
    b_ : Scalar
      Bias unit after fitting.
    losses_ : list
      Number of misclassifications (updates) in each epoch.
    
    """
    def __init__(self, eta=0.01, n_iter=50, random_state=1):
        self.eta = eta
        self.n_iter = n_iter
        self.random_state = random_state
    def fit(self, X, y, C=1):
        """Fit training data.
        
        Parameters
        ----------
        X : {array-like}, shape = [n_examples, n_features]
          Training vectors, where n_examples is the number of 
          examples and n_features is the number of features.
        y : array-like, shape = [n_examples]
          Target values.
        
        Returns
        -------
        self : object
        
        """
        #TODO: change from perceptron logic to soft-margin SVC
        n = y.size # number of samples

        rgen = np.random.RandomState(self.random_state)
        self.w_ = rgen.normal(loc=0.0, scale=0.01,
                              size=X.shape[1])
        self.b_ = np.float64(0.)
        self.losses_ = []
        
        for _ in range(self.n_iter):
            y_hat = []
            for xi, target, i in zip(X, y, range(n)):
                y_hat.append(self.predict(xi))
                update = self.eta * (target - y_hat[i])
                self.w_ += update * xi
                self.b_ += update
                # errors += update != 0.0
            losses = self.hinge_loss(y, y_hat, C)
            self.losses_.append(losses)
        return self
    
    def net_input(self, X):
        """Calculate net input"""
        #TODO: this is perceptron's stuff, change it 
        return np.dot(X, self.w_) + self.b_
    
    def predict(self, X):
        """Return class label after unit step"""
        #TODO: this is perceptron's stuff, change it 
        return np.where(self.net_input(X) >= 0.0, 1, 0)
    
    """
    Given the true labels y, and the labels generated by the linear SVC y_hat,
    Calculate the hinge loss of all samples float
    """

    def hinge_loss(self, y, y_hat, C):
        # zeros = np.zeros_like(y) # Loss vector has same shape as y and y_hat
        vals = 1 - y * y_hat
        # print(f"y: {y}")
        # print(f"y_hat: {y_hat}")
        # print(f"vals: {vals}")
        condition = vals <= 0 
        loss = np.mean(np.where(condition, 0, vals))
        weight_mag = np.linalg.norm(self.w_)
        return C * loss + 0.5 * weight_mag * weight_mag

if __name__ == "__main__":
    # i = 1
    X, y = make_classification(  10, rand_seed= 10)
    print(y)
    lvc = LinearSVC()
    lvc.fit(X, y)
    y_hat = lvc.predict(X)
    print(y_hat)
