import numpy as np
import matplotlib.pyplot as plt
from generator import make_classification 
from plots.part_one import gen_plot
from plots.part_one import display_margins

class LinearSVC:
    """Linear SVC classifier.
    
    Parameters
    ------------
    eta : float
      Learning rate (between 0.0 and 1.0)
    n_iter : int
      Passes over the training dataset.
    random_state : int
      Random number generator seed for random weight 
      initialization.
    
    Attributes
    -----------
    w_ : 1d-array
      Weights after fitting.
    b_ : Scalar
      Bias unit after fitting.
    losses_ : list
      Number of misclassifications (updates) in each epoch.
    
    """
    def __init__(self, eta=0.01, n_iter=50, C = 1, random_state=1):
        self.eta = eta
        self.n_iter = n_iter
        self.random_state = random_state
        self.C = C
    
    def fit(self, X, y):
        """Fit training data.
        
        Parameters
        ----------
        X : {array-like}, shape = [n_examples, n_features]
          Training vectors, where n_examples is the number of 
          examples and n_features is the number of features.
        y : array-like, shape = [n_examples]
          Target values.
        
        Returns
        -------
        self : object
        
        """
        n = y.size # number of samples

        rgen = np.random.RandomState(self.random_state)
        self.w_ = rgen.normal(loc=0.0, scale=0.01,
                              size=X.shape[1])
        self.b_ = np.float64(0.)
        self.losses_ = []
        
        for _ in range(self.n_iter):
            # Adopted from perceptron loop
            y_hat = [] # The guesses of this itteration
            hinge_loss = []   
            for xi, yi in zip(X, y):
                y_hati = self.net_input(xi) # Guess for i'th sample in current itteration
                y_hat.append(y_hati)

                hinge_lossi = self._losses_(yi, y_hati) # i'th loss 
                hinge_loss.append(hinge_lossi)

                if hinge_lossi > 0:  
                    # Gradient, outside margin
                    grad_w = self.w_ - self.C * yi * xi
                    grad_b = - self.C * yi
                else:
                    # Inside the margin, no gradient
                    grad_w = self.w_
                    grad_b = 0

                self.w_ -= self.eta * grad_w
                self.b_ -= self.eta * grad_b
            loss = self._L2_regularization_(hinge_loss)
            self.losses_.append(loss)
        return self
    
    def net_input(self, X):
        """Calculate net input"""
        return np.dot(X, self.w_) + self.b_
    
    def predict(self, X):
        """Return class label after unit step"""
        return np.where(self.net_input(X) >= 0.0, 1, -1)
    
    """
    Given the true labels y, and the labels generated by the linear SVC y_hat,
    Calculate the hinge loss of all samples
    """

    def _L2_regularization_(self, losses):
        # weight_mag = np.linalg.norm(self.w_)
        return np.mean(losses) #+ 0.5 * weight_mag * weight_mag
        # return self.C * np.mean(losses) + 0.5 * weight_mag * weight_mag
    
    """
    The hinge lost function
    """
    def _losses_(self, y, y_hat):
        vals = 1 - y * y_hat

        # If vals[i] is less than zero, put zero, otherwise keep vals[i]
        return np.where((vals <= 0 ), 0, vals)
        

if __name__ == "__main__":
    # i = 1
    X, y, x_test, y_test, a = make_classification(50, rand_seed= 11)
    
    lvc = LinearSVC(n_iter=100, eta=0.01, C=15)
    lvc.fit(X, y)
    y_hat = lvc.predict(X)

    # print(y_hat)
    # gen_plot(X, y, a)
    gen_plot(X, y_hat, a)
    display_margins(X, y, lvc.w_, lvc.b_)

    fig, ax = plt.subplots(figsize=(16,8))
    # print(lvc.losses_)

    ax.plot(range(1, len(lvc.losses_) + 1), (lvc.losses_), marker='')
    ax.set_xlabel('Epochs')
    ax.set_ylabel('Losses')
    ax.set_title("Linear SVC Losses over Epochs")
    plt.show()
